#! /usr/bin/env php
<?php

use Symfony\Component\Console\Application;
require'vendor/autoload.php';

$app = new Application('Task Console','1.0');

try{

//    $pdo = new PDO('mysql:host=localhost;dbname="task','root','admin');
    $pdo= new PDO('sqlite:db.sqlite');

    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);

    $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);


}catch(Exception $exception){

    echo 'Could Not Connect To The Database' . $exception;
    exit(1);
}

$dbAdapter= new Acme\DatabaseAdapter($pdo);
$app->add(new Acme\ShowCommand($dbAdapter));
$app->add(new Acme\AddCommand($dbAdapter));
$app->add(new Acme\CompleteCommand($dbAdapter));
$app->run();